//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acesso
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public int Tipo { get; set; }
        public int GaragemId { get; set; }
        public int VendedorId { get; set; }
        public byte Status { get; set; }
    
        public virtual Garagem Garagem { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
