//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int Id { get; set; }
        public string Foto1 { get; set; }
        public int VeiculoId { get; set; }
        public int GaragemId { get; set; }
    
        public virtual Garagem Garagem { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
