//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public int FormaPgto { get; set; }
        public int VeiculoId { get; set; }
        public int ClientId { get; set; }
        public string Obs { get; set; }
        public int GaragemId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Garagem Garagem { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
